import type { Activity, Project, Task, Priority, TaskStatus, ProjectStatus } from "./store";

const day = 86400000;
const iso = (offsetDays: number) => new Date(Date.now() + offsetDays * day).toISOString().slice(0, 10);
const ts = (offsetDays: number, h = 0) => new Date(Date.now() + offsetDays * day + h * 3600000).toISOString();

const projectDefs: [string, string, ProjectStatus, number, number, number][] = [
  ["Campus Event Platform", "A booking and discovery portal for university societies, venues and ticketed events.", "in_progress", -40, 30, -42],
  ["Inventory Management Portal", "Stock tracking across three warehouses with low-stock alerts and supplier ordering.", "in_progress", -25, 45, -27],
  ["Marketing Analytics Dashboard", "Unified view of campaign spend, attribution and weekly channel performance.", "not_started", 7, 70, -6],
  ["E-Commerce Redesign", "Refresh of product pages, cart and checkout to lift conversion on mobile.", "completed", -90, -10, -95],
  ["Employee Onboarding System", "Guided first-week checklists, document collection and buddy assignments.", "in_progress", -14, 40, -16],
  ["Mobile Banking Prototype", "Clickable prototype for savings goals, transfers and card controls.", "not_started", 14, 60, -3],
  ["Community Health Portal", "A secure patient portal for appointments, care plans and provider messaging.", "in_progress", -18, 55, -20],
  ["Sustainable Packaging Launch", "Coordinate supplier research, prototypes and retail rollout for a lower-waste package.", "in_progress", -8, 35, -10],
  ["Learning Hub Migration", "Move course content, assessments and learner analytics into a unified platform.", "not_started", 20, 90, -2],
  ["Support Operations Refresh", "Improve triage workflows, service-level reporting and the internal knowledge base.", "completed", -120, -15, -125],
  ["Partner API Program", "Publish versioned integrations and onboarding tools for strategic technology partners.", "in_progress", 5, 80, -8],
  ["Quarterly Planning Kit", "Reusable planning templates for goals, dependencies, risks and team reviews.", "completed", -75, -25, -80],
  ["Product Research Repository", "Centralize interview insights, market signals and opportunity briefs for product teams.", "in_progress", -10, 50, -12],
  ["Security Certification Readiness", "Coordinate evidence, control owners and audit milestones for annual certification.", "in_progress", -20, 65, -21],
  ["Customer Success Playbook", "Standardize customer health reviews, renewal planning and escalation handoffs.", "in_progress", -16, 38, -18],
  ["Internal Design System", "Build shared components, accessibility guidance and adoption support for product teams.", "in_progress", -30, 75, -35],
  ["Data Warehouse Modernization", "Migrate reporting pipelines to a governed, reliable and scalable warehouse.", "in_progress", -45, 95, -48],
  ["Sustainability Reporting", "Prepare auditable environmental metrics and a clear annual impact report.", "not_started", 4, 80, -4],
  ["Field Sales Enablement", "Equip regional teams with current collateral, training and account planning tools.", "in_progress", -8, 42, -10],
  ["Alumni Engagement Program", "Create a year-round engagement calendar for graduates, mentors and donors.", "not_started", 12, 72, -2],
  ["Facilities Maintenance Portal", "Give facilities teams a single place to track requests, assets and preventative work.", "in_progress", -22, 56, -23],
  ["Volunteer Coordination Hub", "Match volunteers to shifts, training and community-service opportunities.", "in_progress", -5, 44, -6],
  ["Grants Management Workspace", "Track grant applications, reporting obligations and funded-program outcomes.", "not_started", 9, 90, -1],
  ["Podcast Network Launch", "Coordinate show development, production calendars and audience growth experiments.", "in_progress", -12, 36, -14],
  ["AI Knowledge Assistant", "Prototype a trustworthy internal assistant grounded in approved company knowledge.", "in_progress", -18, 68, -20],
  ["Internationalization Rollout", "Prepare the product, support content and operations for new regional markets.", "not_started", 18, 110, -3],
  ["Finance Close Automation", "Reduce manual reconciliation work and improve close-cycle visibility for finance.", "in_progress", -35, 58, -37],
  ["User Research Operations", "Establish participant management, consent and insight-sharing workflows.", "in_progress", -15, 52, -16],
  ["Community Moderation Program", "Create consistent moderation practices, tooling and incident response routines.", "not_started", 5, 64, -5],
  ["Disaster Recovery Program", "Validate recovery procedures and restore-time objectives across critical services.", "in_progress", -28, 84, -30],
  ["Brand Refresh Toolkit", "Deliver reusable visual assets, messaging and launch guidance for every team.", "completed", -70, -5, -75],
  ["Marketplace Seller Experience", "Improve onboarding, catalog quality and support journeys for marketplace sellers.", "in_progress", -11, 62, -13],
];

const taskDefs: [number, string, Priority, TaskStatus, number, string[]][] = [
  [0, "Implement authentication flow", "high", "completed", -12, ["backend", "security"]],
  [0, "Design event listing page", "medium", "completed", -8, ["design"]],
  [0, "Build venue booking calendar", "high", "in_progress", 3, ["frontend"]],
  [0, "Add ticket checkout validation", "high", "pending", 6, ["backend", "bug"]],
  [0, "Test project creation flow", "low", "pending", 12, ["testing"]],
  [1, "Create database schema", "high", "completed", -15, ["backend"]],
  [1, "Build responsive navigation", "medium", "completed", -6, ["frontend", "design"]],
  [1, "Fix dashboard filtering", "high", "in_progress", 1, ["bug", "frontend"]],
  [1, "Implement low-stock alerts", "medium", "pending", 9, ["backend"]],
  [1, "Add supplier order form validation", "medium", "pending", 14, ["backend", "testing"]],
  [2, "Define KPI dictionary with marketing", "medium", "pending", 10, ["research"]],
  [2, "Create analytics chart components", "high", "pending", 18, ["frontend", "design"]],
  [2, "Connect ad spend import", "low", "pending", 25, ["backend"]],
  [3, "Design project overview", "medium", "completed", -60, ["design"]],
  [3, "Optimize mobile layout", "high", "completed", -40, ["frontend", "design"]],
  [3, "Rebuild cart drawer", "high", "completed", -30, ["frontend"]],
  [3, "Run checkout usability test", "medium", "completed", -14, ["research", "testing"]],
  [4, "Implement task completion", "medium", "completed", -5, ["backend"]],
  [4, "Draft first-week checklist content", "low", "completed", -3, ["research"]],
  [4, "Add form validation", "medium", "in_progress", 2, ["frontend", "bug"]],
  [4, "Build document upload step", "high", "pending", 0, ["frontend"]],
  [4, "Assign onboarding buddies", "low", "pending", 8, ["research"]],
  [5, "Map savings goal user journey", "medium", "pending", 16, ["research", "design"]],
  [5, "Prototype card freeze interaction", "high", "pending", 21, ["design"]],
  [5, "Review transfer screens with compliance", "medium", "pending", 28, ["research"]],
  [6, "Map appointment booking journey", "high", "completed", -9, ["research", "design"]],
  [6, "Build provider messaging inbox", "high", "in_progress", 4, ["frontend", "backend"]],
  [6, "Add consent preferences", "medium", "pending", 12, ["security", "backend"]],
  [6, "Run accessibility review", "low", "pending", 18, ["testing"]],
  [7, "Shortlist material suppliers", "medium", "completed", -4, ["research"]],
  [7, "Approve package prototypes", "high", "in_progress", 7, ["design", "review"]],
  [7, "Prepare retail launch checklist", "medium", "pending", 20, ["planning"]],
  [7, "Measure packaging waste reduction", "low", "pending", 32, ["analytics"]],
  [8, "Audit legacy course content", "high", "pending", 15, ["research"]],
  [8, "Define migration mapping", "medium", "pending", 24, ["backend"]],
  [8, "Design learner progress view", "medium", "pending", 35, ["frontend", "design"]],
  [8, "Pilot migration with instructors", "low", "pending", 48, ["testing"]],
  [9, "Document support escalation rules", "medium", "completed", -22, ["operations"]],
  [9, "Create service-level dashboard", "high", "completed", -18, ["analytics", "frontend"]],
  [9, "Archive outdated help articles", "low", "completed", -12, ["content"]],
  [10, "Publish partner authentication guide", "high", "in_progress", 6, ["documentation", "security"]],
  [10, "Build webhook retry handling", "high", "pending", 16, ["backend"]],
  [10, "Create integration status page", "medium", "pending", 27, ["frontend"]],
  [11, "Collect team planning feedback", "low", "completed", -30, ["research"]],
  [11, "Refresh quarterly goal templates", "medium", "completed", -24, ["planning", "design"]],
  [11, "Publish dependency review guide", "low", "completed", -19, ["documentation"]],
  [12, "Consolidate interview notes", "high", "completed", -7, ["research", "content"]],
  [12, "Tag competitor observations", "medium", "in_progress", 4, ["research", "analytics"]],
  [12, "Publish opportunity brief template", "medium", "pending", 13, ["documentation", "planning"]],
  [12, "Schedule monthly insight review", "low", "pending", 22, ["operations"]],
  [13, "Map control owners", "high", "completed", -9, ["security", "planning"]],
  [13, "Collect audit evidence", "high", "in_progress", 2, ["security", "documentation"]],
  [13, "Run access-control review", "medium", "pending", 16, ["security", "testing"]],
  [13, "Prepare auditor walkthrough", "medium", "pending", 31, ["documentation", "review"]],
  [14, "Define customer health signals", "high", "completed", -6, ["analytics", "research"]],
  [14, "Draft renewal review agenda", "medium", "in_progress", 3, ["planning", "content"]],
  [14, "Publish escalation matrix", "medium", "pending", 14, ["operations", "documentation"]],
  [14, "Train success managers", "low", "pending", 28, ["training"]],
  [15, "Audit shared UI patterns", "high", "completed", -14, ["design", "frontend"]],
  [15, "Build accessible form primitives", "high", "in_progress", 5, ["frontend", "testing"]],
  [15, "Write component usage guide", "medium", "pending", 18, ["documentation", "design"]],
  [15, "Host adoption office hours", "low", "pending", 34, ["operations"]],
  [16, "Inventory legacy data sources", "high", "completed", -20, ["backend", "analytics"]],
  [16, "Model governed reporting layer", "high", "in_progress", 7, ["backend", "planning"]],
  [16, "Migrate executive dashboards", "medium", "pending", 35, ["analytics", "frontend"]],
  [16, "Run reliability load test", "medium", "pending", 57, ["testing", "backend"]],
  [17, "Confirm reporting framework", "high", "pending", 11, ["research", "documentation"]],
  [17, "Collect supplier emissions data", "medium", "pending", 28, ["operations", "analytics"]],
  [17, "Review materiality assessment", "medium", "pending", 49, ["review", "planning"]],
  [17, "Draft impact report narrative", "low", "pending", 72, ["content"]],
  [18, "Refresh account planning template", "high", "completed", -4, ["planning", "content"]],
  [18, "Record discovery-call training", "medium", "in_progress", 6, ["training", "sales"]],
  [18, "Launch regional content library", "medium", "pending", 19, ["frontend", "content"]],
  [18, "Measure playbook adoption", "low", "pending", 33, ["analytics"]],
  [19, "Segment alumni audiences", "high", "pending", 17, ["research", "analytics"]],
  [19, "Plan mentor matching campaign", "medium", "pending", 29, ["planning", "content"]],
  [19, "Build event registration flow", "medium", "pending", 48, ["frontend"]],
  [19, "Prepare donor update", "low", "pending", 65, ["content"]],
  [20, "Catalog high-priority assets", "high", "completed", -10, ["operations", "research"]],
  [20, "Design maintenance request form", "medium", "in_progress", 2, ["frontend", "design"]],
  [20, "Configure preventative schedules", "high", "pending", 18, ["backend", "planning"]],
  [20, "Pilot technician mobile view", "low", "pending", 39, ["testing", "frontend"]],
  [21, "Map recurring volunteer shifts", "high", "completed", -3, ["planning"]],
  [21, "Create training checklist", "medium", "in_progress", 4, ["training", "documentation"]],
  [21, "Build availability matching", "high", "pending", 15, ["frontend", "backend"]],
  [21, "Publish recognition plan", "low", "pending", 30, ["content"]],
  [22, "Define application review stages", "high", "pending", 13, ["planning", "operations"]],
  [22, "Create reporting deadline calendar", "medium", "pending", 31, ["frontend", "documentation"]],
  [22, "Build budget tracking worksheet", "medium", "pending", 52, ["analytics", "planning"]],
  [22, "Prepare award notification kit", "low", "pending", 76, ["content"]],
  [23, "Finalize pilot-show brief", "high", "completed", -5, ["content", "planning"]],
  [23, "Book studio recording blocks", "medium", "in_progress", 3, ["operations"]],
  [23, "Create episode promotion template", "medium", "pending", 12, ["marketing", "design"]],
  [23, "Review launch audience data", "low", "pending", 25, ["analytics"]],
  [24, "Curate approved knowledge sources", "high", "completed", -8, ["documentation", "security"]],
  [24, "Prototype retrieval experience", "high", "in_progress", 5, ["frontend", "backend"]],
  [24, "Evaluate response quality", "medium", "pending", 21, ["testing", "research"]],
  [24, "Draft responsible-use guidance", "medium", "pending", 40, ["security", "documentation"]],
  [25, "Prioritize launch markets", "high", "pending", 20, ["research", "planning"]],
  [25, "Externalize product copy", "high", "pending", 42, ["frontend", "content"]],
  [25, "Localize support workflows", "medium", "pending", 68, ["operations", "documentation"]],
  [25, "Run regional launch review", "low", "pending", 96, ["review"]],
  [26, "Map reconciliation bottlenecks", "high", "completed", -12, ["research", "finance"]],
  [26, "Automate account matching", "high", "in_progress", 4, ["backend", "finance"]],
  [26, "Build close-status dashboard", "medium", "pending", 18, ["frontend", "analytics"]],
  [26, "Validate monthly close controls", "medium", "pending", 37, ["testing", "security"]],
  [27, "Select participant panel tool", "high", "completed", -7, ["research", "operations"]],
  [27, "Create consent template", "medium", "in_progress", 3, ["documentation", "security"]],
  [27, "Set up insight repository", "medium", "pending", 17, ["frontend", "research"]],
  [27, "Publish research intake guide", "low", "pending", 32, ["documentation"]],
  [28, "Write moderation principles", "high", "pending", 10, ["policy", "content"]],
  [28, "Configure incident intake", "high", "pending", 24, ["backend", "operations"]],
  [28, "Train volunteer moderators", "medium", "pending", 43, ["training"]],
  [28, "Review enforcement metrics", "low", "pending", 58, ["analytics", "review"]],
  [29, "Review critical service inventory", "high", "completed", -11, ["security", "operations"]],
  [29, "Update recovery runbooks", "high", "in_progress", 6, ["documentation", "backend"]],
  [29, "Schedule recovery simulation", "medium", "pending", 27, ["testing", "planning"]],
  [29, "Capture improvement actions", "low", "pending", 50, ["review"]],
  [30, "Approve brand voice principles", "high", "completed", -35, ["content", "design"]],
  [30, "Produce presentation templates", "medium", "completed", -21, ["design"]],
  [30, "Publish asset library", "medium", "completed", -12, ["frontend", "content"]],
  [30, "Share launch office-hours plan", "low", "completed", -6, ["operations"]],
  [31, "Interview new sellers", "high", "completed", -5, ["research"]],
  [31, "Simplify catalog setup", "high", "in_progress", 4, ["frontend", "design"]],
  [31, "Add onboarding progress view", "medium", "pending", 20, ["frontend", "analytics"]],
  [31, "Test support handoff", "low", "pending", 41, ["testing", "operations"]],
];

export function seedFor(userId: string) {
  const projects: Project[] = projectDefs.map(([name, description, status, s, e, c], i) => ({
    id: `${userId}_p${i}`, userId, name, description, status, startDate: iso(s), endDate: iso(e), createdDate: ts(c),
  }));
  const tasks: Task[] = taskDefs.map(([pi, name, priority, status, due, tags], i) => ({
    id: `${userId}_t${i}`, userId, projectId: projects[pi]!.id, name,
    description: `${name} for ${projects[pi]!.name}.`, priority, status, dueDate: iso(due), tags,
    createdDate: ts(Math.min(due, 0) - 10 + (i % 5), i),
  }));
  const msgs: [string, string, number][] = [
    ["task_completed", "Completed task — Draft first-week checklist content", -0.1],
    ["task_priority", "Changed task priority — Fix dashboard filtering → High", -0.4],
    ["task_created", "Created task — Build document upload step", -1],
    ["project_status", "Changed project status — Employee Onboarding System → In Progress", -2],
    ["task_completed", "Completed task — Implement task completion", -3],
    ["project_created", "Created project — Mobile Banking Prototype", -3.2],
    ["project_updated", "Updated project — Marketing Analytics Dashboard", -5],
    ["task_deleted", "Deleted task — Legacy CSV export", -6],
  ];
  const activities: Activity[] = msgs.map(([type, message, d], i) => ({ id: `${userId}_a${i}`, userId, type, message, createdAt: ts(d) }));
  return { projects, tasks, activities };
}
